"""Metodos de String"""
print('prueba'.capitalize())
print('John Eliseo'.center(20,'*'))
print('John Eliseo'.count('o'))
print('otoño'.encode('utf-8'))
print('John'.endswith('n'))
print('Carlos'.endswith('o'))
print('smartphone'.find('a'))
print('smartphone'.find('f'))
print('La casa es {}'.format('muy bonita!'))
print('automovil'.index('l'))
print('manzanas10'.isalnum())
print('pruebas string'.isalnum())
print('pruebas'.isalpha())
print('pruebas10'.isalpha())
print('10.5'.isdecimal())
print('10'.isdecimal())
print('10s'.isdigit())
print('5'.isdigit())
print('Pruebas'.islower())
print('pruebas'.islower())
print('messi 10'.isnumeric())
print('100000'.isnumeric())
print('imprimmir'.isprintable())
print('   '.isspace());
print('textosinespacios'.isspace())
print('Titulo'.istitle())
print('titulo'.istitle())
print('minusculas'.isupper())
print('MAYUSCULAS'.isupper())
print('","'.join(['a','b','c']))
print('MAYUSCULAS'.lower())
print('tomate'.replace('to','cal'))
print('tamalo'.replace('t','m'))
print('Hola John'.split(" "))
print('John'.startswith('P'))
print('Eliseo'.startswith('E'))
print('Eliseo'.startswith('e'))
print(' Jose ')
print(' Jose '.strip())
print('Eliseo'.swapcase())
print('eliseo'.swapcase())
print('jose maria'.title())
print('carlos saenz'.upper())
print('Jose'.zfill(10))

"""s1 = ' python es genial! '
s2 = "prueba"
s3 = "  prueba"
s4 = " Hola Mundo "
print(s4.split(" "))
print(s3.lstrip())
print(s2.rjust(10))
print(s2.ljust(10))
print(s1.center(10))
print(s1.find('ue'))
print(s1.index('P'))"""
a_string = '1,2,3,5'.split(',')
print(a_string)
print(' python es genial! ')
print(' python es genial! '.strip())
print('py'.capitalize().startswith('Py'))


nombre = input('Digite su nombre')
print('Su nombre Esta en Mayuscula?: ', nombre.isupper())
